#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58E11BB1E414D9AD (phil@ipom.com)
#
Name     : iptstate
Version  : 2.2.6
Release  : 1
URL      : https://github.com/jaymzh/iptstate/releases/download/v2.2.6/iptstate-2.2.6.tar.bz2
Source0  : https://github.com/jaymzh/iptstate/releases/download/v2.2.6/iptstate-2.2.6.tar.bz2
Source99 : https://github.com/jaymzh/iptstate/releases/download/v2.2.6/iptstate-2.2.6.tar.bz2.asc
Summary  : Display IP Tables state table information in a "top"-like interface
Group    : Development/Tools
License  : Zlib
Requires: iptstate-bin = %{version}-%{release}
Requires: iptstate-license = %{version}-%{release}
Requires: iptstate-man = %{version}-%{release}
BuildRequires : libnetfilter_conntrack-dev
BuildRequires : pkgconfig(ncursesw)
Patch1: 0001-Add-destdir-support.patch

%description
IP Tables State (iptstate) was originally written to
 impliment the "state top" feature of IP Filter.
 "State top" displays the states held by your stateful 
 firewall in a "top"-like manner.

 Since IP Tables doesn't have a built in way to easily
 display this information even once, an option was
 added to just display the state table once and exit.

%package bin
Summary: bin components for the iptstate package.
Group: Binaries
Requires: iptstate-license = %{version}-%{release}
Requires: iptstate-man = %{version}-%{release}

%description bin
bin components for the iptstate package.


%package license
Summary: license components for the iptstate package.
Group: Default

%description license
license components for the iptstate package.


%package man
Summary: man components for the iptstate package.
Group: Default

%description man
man components for the iptstate package.


%prep
%setup -q -n iptstate-2.2.6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550790921
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1550790921
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/iptstate
cp LICENSE %{buildroot}/usr/share/package-licenses/iptstate/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iptstate

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iptstate/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/iptstate.8
